version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "sh"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
        - ./:/app
    environment:
        PORT: 8080
    networks:
      - default

networks:
  default:
    name: localdev

volumes:
  database_data:
    driver: local
