version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "1234:1234"
    expose:
      - 1234
      - 8080
      - 8081
    volumes:
        - ./:/app
    environment:
        PORT: 1234
    networks:
      - default
      - gateway

networks:
  default:
    name: localdev
  gateway:
    name: gateway
volumes:
  local:
    driver: local
