version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "npm start"
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
        - .:/app
    links:
      - database
    depends_on:
      - database
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example
        POSTGRES_DB: postgres
    networks:
      - default

